### PR TITLE
Nanoid version increase

### PR DESCRIPTION
**Pull request by yukosgiti**
I updated `nanoid` to version `3.10.3` and updated the necessary files.

**FYI**: `package.json` also has `react` and `react-dom` updated & their place changed for me to use `flume` as a local library. So you may change those.

### CODE REVIEW

**Comment by chrisjpatty** [comment]
OMG did you figure out the math for zooming towards the mouse for me?! I have been wanting to implement that forever but was too lazy to calculate it. Thanks a ton!

**Comment by yukosgiti** [comment]
No problem. I like the library a lot. That was going to be a different pull request though. I wasn't aware my pushes would also be pushed to the pull request. Still learning how github works lol

**Comment by chrisjpatty** [comment]
No worries, happy to handle it all in one PR as long as you believe the changes to be stable. Thanks again

**Comment by chrisjpatty** [comment]
This is working great, thanks again for the great contribution!

**Pull request merged**
